version: "3.7"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5555:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: fastapiuser
      POSTGRES_PASSWORD: fastapipass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: fleamarket
    hostname: postgres
    restart: always
    user: root
